services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stepik_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/stepik_db
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    command: celery -A app.core.celery_app worker --loglevel=info
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/stepik_db
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  pgdata: