"""add test cases

Revision ID: b9b2f972d9d3
Revises: dd61889e96d4
Create Date: 2026-05-13 18:57:06.834385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9b2f972d9d3'
down_revision: Union[str, Sequence[str], None] = 'dd61889e96d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('input_data', sa.Text(), nullable=True),
    sa.Column('expected_output', sa.Text(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cases_id'), 'test_cases', ['id'], unique=False)
    op.create_index(op.f('ix_test_cases_task_id'), 'test_cases', ['task_id'], unique=False)
    op.drop_column('tasks', 'test_output')
    op.drop_column('tasks', 'test_input')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('test_input', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('test_output', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_test_cases_task_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_id'), table_name='test_cases')
    op.drop_table('test_cases')
    # ### end Alembic commands ###
